#!/bin/bash
ssh -i id_rsa root@192.168.1.5 /bin/bash << EOF
if ps ax | grep -v grep | grep forever > /dev/null
then
  echo "forever is running, kill it and restart anyway"
  killall node
else
  echo "forever is not running"
fi

forever start --uid "copter" -a /root/copterjs/src/server/index.js
EOF
