#!/bin/bash
source environment
ssh -i id_rsa ${USER_NAME}@${IP_ADDR} /bin/bash << EOF
if ps ax | grep -v grep | grep forever > /dev/null
then
  echo "forever is running, kill it"
  killall node
else
  echo "forever is not running"
fi
EOF
